/* Copie de family-data.json lisible par double-clic (générée par admin.html). Ne pas modifier à la main. */
window.FAMILY_DATA = {
  "site": {
    "titre": "Plusieurs Branches, une Même Racine",
    "sousTitre": "Main dans la main, de génération en génération."
  },
  "grandesFamilles": [
    {
      "id": "jouenang",
      "nom": "Jouenang",
      "description": "Descendance de Jouenang Abel.",
      "famillePrincipaleId": "famille-abel-martine"
    },
    {
      "id": "djampou",
      "nom": "Djampou",
      "description": "Descendance de Papa Thomas",
      "famillePrincipaleId": "djampou"
    },
    {
      "id": "tchoungang",
      "nom": "Chana",
      "description": "descendance de Maman Cathérine Tchoungang",
      "famillePrincipaleId": "tchoungang"
    }
  ],
  "familles": [
    {
      "id": "famille-abel-martine",
      "nom": "Famille Jouenang",
      "grandeFamilleId": "jouenang",
      "pereId": "abel",
      "mereId": "martine",
      "ordre": 1,
      "photos": []
    },
    {
      "id": "famille-gilbert-gilbert-epouse",
      "nom": "Famille Kamnang",
      "grandeFamilleId": "jouenang",
      "pereId": "gilbert",
      "mereId": "gilbert-epouse",
      "ordre": 1,
      "photos": []
    },
    {
      "id": "famille-jean-lebel-jean-lebel-epouse",
      "nom": "Famille Ngopnang",
      "grandeFamilleId": "jouenang",
      "pereId": "jean-lebel",
      "mereId": "jean-lebel-epouse",
      "ordre": 3
    },
    {
      "id": "famille-berthine-epoux-berthine",
      "nom": "Famille Fokoua",
      "grandeFamilleId": "jouenang",
      "pereId": "berthine-epoux",
      "mereId": "berthine",
      "ordre": 4,
      "photos": []
    },
    {
      "id": "famille-dagobert-dagobert-epouse",
      "nom": "Famille Djapou",
      "grandeFamilleId": "jouenang",
      "pereId": "dagobert",
      "mereId": "dagobert-epouse",
      "ordre": 5
    },
    {
      "id": "famille-claude-claude-epouse",
      "nom": "Famille Djinang",
      "grandeFamilleId": "jouenang",
      "pereId": "claude",
      "mereId": "claude-epouse",
      "ordre": 6,
      "photos": []
    },
    {
      "id": "famille-jules-jules-epouse",
      "nom": "Famille Komguep",
      "grandeFamilleId": "jouenang",
      "pereId": "jules",
      "mereId": "jules-epouse",
      "ordre": 7,
      "photos": []
    },
    {
      "id": "famille-abel-cecile",
      "nom": "Famille Jouenang",
      "grandeFamilleId": "jouenang",
      "pereId": "abel",
      "mereId": "cecile",
      "ordre": 2,
      "photos": []
    },
    {
      "id": "famille-bertin-bertin-epouse",
      "nom": "Famille Poka'a",
      "grandeFamilleId": "jouenang",
      "pereId": "bertin",
      "mereId": "bertin-epouse",
      "ordre": 14,
      "photos": []
    },
    {
      "id": "famille-nadege-epoux-nadege",
      "nom": "Famille Mouafo",
      "grandeFamilleId": "jouenang",
      "pereId": "nadege-epoux",
      "mereId": "nadege",
      "ordre": 15,
      "photos": []
    },
    {
      "id": "famille-alvine-epoux-alvine",
      "nom": "Famille Guenang",
      "grandeFamilleId": "jouenang",
      "pereId": "alvine-epoux",
      "mereId": "alvine",
      "ordre": 17
    },
    {
      "id": "famille-alain",
      "nom": "Famille Tchiemegne",
      "grandeFamilleId": "jouenang",
      "pereId": "alain",
      "mereId": null,
      "ordre": 10
    },
    {
      "id": "famille-valerie",
      "nom": "Famille Nagfack",
      "grandeFamilleId": "jouenang",
      "pereId": null,
      "mereId": "valerie",
      "ordre": 13
    },
    {
      "id": "famille-sylvia",
      "nom": "Famille Sotche",
      "grandeFamilleId": "jouenang",
      "pereId": null,
      "mereId": "sylvia",
      "ordre": 16
    },
    {
      "id": "tidjouon",
      "nom": "Famille Tidjouon",
      "grandeFamilleId": "djampou",
      "pereId": "pascal-yves-tidjouon",
      "mereId": "louise-pelagie-tchopkam-djampou",
      "ordre": 11,
      "photos": []
    },
    {
      "id": "atangana",
      "nom": "Famille Atangana",
      "grandeFamilleId": "tchoungang",
      "pereId": "serge-valery-atangana-mbanga",
      "mereId": "theodora-ange-noel-nguekam-tchamabong",
      "ordre": 12,
      "photos": [],
      "niveau": 2
    },
    {
      "id": "famille-tchiedjop",
      "nom": "Famille Tchiedjop",
      "grandeFamilleId": "jouenang",
      "pereId": "lebel-tchiedjop",
      "mereId": "julienne-djomo",
      "niveau": "aieul",
      "photos": [],
      "ascendants": true
    },
    {
      "id": "famille-koutchadjio",
      "nom": "Famille Koutchadjio",
      "grandeFamilleId": "jouenang",
      "pereId": "webo-koutchadjio",
      "mereId": "emilienne-sotche",
      "niveau": "aieul",
      "photos": [],
      "ascendants": true
    },
    {
      "id": "famille-guepning",
      "nom": "Famille Nguepnin",
      "grandeFamilleId": "jouenang",
      "pereId": "abel-guepning",
      "mereId": "josephine-miyo",
      "niveau": "aieul",
      "photos": [],
      "ascendants": true
    },
    {
      "id": "djampou",
      "nom": "Famille Djampou",
      "grandeFamilleId": "djampou",
      "pereId": "thomas-djampou",
      "mereId": "jeanne-noumboue",
      "niveau": 0,
      "ordre": 4,
      "photos": []
    },
    {
      "id": "wandji",
      "nom": "Famille Wandji",
      "grandeFamilleId": "tchoungang",
      "pereId": null,
      "mereId": "lydie-wandji",
      "ordre": 2,
      "photos": []
    },
    {
      "id": "tchoungang",
      "nom": "Famille Chana",
      "grandeFamilleId": "tchoungang",
      "pereId": "joseph-chana",
      "mereId": "catherine-tchoungang",
      "niveau": 0,
      "ordre": 3,
      "photos": []
    },
    {
      "id": "famille-nguepdjop",
      "nom": "Famille Nguepdjop",
      "grandeFamilleId": "jouenang",
      "pereId": "crepin-nguepdjop",
      "mereId": "regine-djouonang",
      "ordre": 9,
      "photos": []
    },
    {
      "id": "famille-fotso",
      "nom": "Famille Fotso Kevin",
      "grandeFamilleId": "jouenang",
      "pereId": "berthine-enfant-1",
      "mereId": "maria",
      "niveau": 2,
      "ordre": 4,
      "photos": []
    },
    {
      "id": "famille-piegouong",
      "nom": "Famille Piegouong Brice",
      "grandeFamilleId": "jouenang",
      "pereId": "gilbert-enfant-3",
      "mereId": "agnes-edzimbi",
      "niveau": 2,
      "ordre": 3,
      "photos": []
    },
    {
      "id": "famille-jouenang",
      "nom": "Famille Jouenang Valère",
      "grandeFamilleId": "jouenang",
      "pereId": "gilbert-enfant-2",
      "mereId": "regine-blanche",
      "niveau": 2,
      "ordre": 2,
      "photos": []
    },
    {
      "id": "tchonkap",
      "nom": "Famille Tchonkap",
      "grandeFamilleId": null,
      "pereId": "osee-tchonkap",
      "mereId": "marcelline-yimga",
      "niveau": "aieul",
      "photos": [],
      "ascendants": true
    },
    {
      "id": "kapnang",
      "nom": "Famille Kapnang",
      "grandeFamilleId": "jouenang",
      "pereId": "papa-kapnang",
      "mereId": "maman-guenang",
      "niveau": "aieul",
      "photos": [],
      "ascendants": true
    },
    {
      "id": "nagmegne",
      "nom": "Famille Nagmegne",
      "grandeFamilleId": "jouenang",
      "pereId": "papa-nagmegne",
      "mereId": "maman-kaptchouang",
      "niveau": "aieul",
      "photos": [],
      "ascendants": true
    },
    {
      "id": "famille-kouonang",
      "nom": "Famille Kouonang",
      "grandeFamilleId": "jouenang",
      "pereId": "papa-kouonang",
      "mereId": "maman-meliedje",
      "niveau": "aieul",
      "photos": [],
      "ascendants": true
    },
    {
      "id": "famille-webo-sawag",
      "nom": "Famille Webo Sawag",
      "grandeFamilleId": "jouenang",
      "pereId": "papa-webo-sawag",
      "mereId": "maman-komguep",
      "niveau": "aieul",
      "photos": [],
      "ascendants": true
    },
    {
      "id": "famille-djapou-aieul",
      "nom": "Famille Djapou (Aïeul)",
      "grandeFamilleId": "jouenang",
      "pereId": "papa-djapou",
      "mereId": "maman-ndap",
      "niveau": "aieul",
      "photos": [],
      "ascendants": true
    },
    {
      "id": "famille-notsa-a",
      "nom": "Famille Notsa'a",
      "grandeFamilleId": "jouenang",
      "pereId": "papa-notsa-a",
      "mereId": "maman-tchatchouang-meliedje",
      "niveau": "aieul",
      "photos": [],
      "ascendants": true
    },
    {
      "id": "famille-nkuemo-sielalie",
      "nom": "Famille Nkuemo",
      "grandeFamilleId": "jouenang",
      "pereId": "gaetan-nkuemo-sielalie",
      "mereId": "gilbert-enfant-1",
      "niveau": 2,
      "ordre": 1,
      "photos": []
    },
    {
      "id": "famille-djongang",
      "nom": "Famille Djongang",
      "grandeFamilleId": "djampou",
      "pereId": "michel-djongang",
      "mereId": "sidonie-claire-tchonang-djampou",
      "photos": [],
      "ordre": 8
    },
    {
      "id": "famille-nguekam-2",
      "nom": "Famille Nguekam",
      "grandeFamilleId": "tchoungang",
      "pereId": "charles-nguekam-2",
      "mereId": "irene-tiengoue",
      "photos": []
    },
    {
      "id": "famille-tenkam",
      "nom": "Famille Tenkam",
      "grandeFamilleId": "tchoungang",
      "pereId": "jean-tenkam",
      "mereId": "anne-ngoungue",
      "photos": [],
      "niveau": "aieul",
      "ascendants": true
    },
    {
      "id": "famille-domkam",
      "nom": "Famille Domkam",
      "grandeFamilleId": "tchoungang",
      "pereId": "moise-domkam-2",
      "mereId": null,
      "photos": []
    },
    {
      "id": "famille-kouonang-2",
      "nom": "Famille Kouonang",
      "grandeFamilleId": "jouenang",
      "pereId": null,
      "mereId": "emilienne-kouonang",
      "photos": [],
      "niveau": "aieul",
      "ascendants": true
    }
  ],
  "personnes": [
    {
      "id": "abel",
      "prenom": "Abel",
      "nom": "Jouenang",
      "sexe": "M",
      "moisNaissance": null,
      "anneeNaissance": 1934,
      "photo": "photos/abel-jouenang.jpg",
      "familleId": "famille-tchiedjop",
      "grandeFamilleId": "jouenang",
      "jourNaissance": null,
      "rangNaissance": null,
      "decede": true,
      "jourDeces": 25,
      "moisDeces": 6,
      "anneeDeces": 2009
    },
    {
      "id": "martine",
      "prenom": "Martine",
      "nom": "Menzefo",
      "sexe": "F",
      "moisNaissance": 8,
      "anneeNaissance": 1936,
      "photo": "photos/martine-menzefo.jpg",
      "familleId": "famille-guepning",
      "grandeFamilleId": "jouenang",
      "jourNaissance": 26,
      "rangNaissance": 2,
      "decede": true,
      "jourDeces": 9,
      "moisDeces": 3,
      "anneeDeces": 1973
    },
    {
      "id": "gilbert",
      "prenom": "Gilbert",
      "nom": "Kamnang",
      "sexe": "M",
      "moisNaissance": 9,
      "anneeNaissance": null,
      "photo": "photos/gilbert.jpeg",
      "familleId": "famille-abel-martine",
      "grandeFamilleId": "jouenang",
      "jourNaissance": 9,
      "rangNaissance": 1,
      "decede": true,
      "jourDeces": 4,
      "moisDeces": 4,
      "anneeDeces": 2026
    },
    {
      "id": "gilbert-epouse",
      "prenom": "Marie",
      "nom": "Chimi",
      "sexe": "F",
      "moisNaissance": 10,
      "anneeNaissance": null,
      "photo": "photos/marie-chimi.jpg",
      "familleId": null,
      "grandeFamilleId": "jouenang",
      "jourNaissance": 8,
      "rangNaissance": null
    },
    {
      "id": "gilbert-enfant-1",
      "prenom": "Arlette Nina",
      "nom": "Djomo",
      "sexe": "F",
      "moisNaissance": 10,
      "anneeNaissance": null,
      "photo": "",
      "familleId": "famille-gilbert-gilbert-epouse",
      "grandeFamilleId": "jouenang",
      "jourNaissance": 17,
      "rangNaissance": 1
    },
    {
      "id": "gilbert-enfant-2",
      "prenom": "Yannick Valère",
      "nom": "Jouenang",
      "sexe": "M",
      "moisNaissance": 6,
      "anneeNaissance": null,
      "photo": "photos/yannick-valere-jouenang.jpg",
      "familleId": "famille-gilbert-gilbert-epouse",
      "grandeFamilleId": "jouenang",
      "rangNaissance": 2,
      "jourNaissance": 2
    },
    {
      "id": "gilbert-enfant-3",
      "prenom": "Brice",
      "nom": "Piegouong",
      "sexe": "M",
      "moisNaissance": 9,
      "anneeNaissance": null,
      "photo": "",
      "familleId": "famille-gilbert-gilbert-epouse",
      "grandeFamilleId": "jouenang",
      "jourNaissance": 2,
      "rangNaissance": 3
    },
    {
      "id": "gilbert-enfant-4",
      "prenom": "Ines",
      "nom": "Menzefo",
      "sexe": "F",
      "moisNaissance": 9,
      "anneeNaissance": null,
      "photo": "",
      "familleId": "famille-gilbert-gilbert-epouse",
      "grandeFamilleId": "jouenang",
      "jourNaissance": 30,
      "rangNaissance": 4
    },
    {
      "id": "gilbert-enfant-5",
      "prenom": "Ange Dany",
      "nom": "Lowe",
      "sexe": "F",
      "moisNaissance": 11,
      "anneeNaissance": null,
      "photo": "photos/ange-dany-lowe.jpg",
      "familleId": "famille-gilbert-gilbert-epouse",
      "grandeFamilleId": "jouenang",
      "jourNaissance": 17,
      "rangNaissance": 5
    },
    {
      "id": "gilbert-enfant-6",
      "prenom": "Darline",
      "nom": "Wakam",
      "sexe": "F",
      "moisNaissance": 6,
      "anneeNaissance": null,
      "photo": "photos/darline-wakam.jpg",
      "familleId": "famille-gilbert-gilbert-epouse",
      "grandeFamilleId": "jouenang",
      "rangNaissance": 6,
      "jourNaissance": 10
    },
    {
      "id": "jean-lebel",
      "prenom": "Jean-Lebel",
      "nom": "Ngopnang",
      "sexe": "M",
      "moisNaissance": 7,
      "anneeNaissance": null,
      "photo": "photos/lebel.jpeg",
      "familleId": "famille-abel-martine",
      "grandeFamilleId": "jouenang",
      "jourNaissance": 3,
      "rangNaissance": 2
    },
    {
      "id": "jean-lebel-epouse",
      "prenom": "Caroline Isabelle",
      "nom": "Ouandji Ketcheuzeu",
      "sexe": "F",
      "moisNaissance": 2,
      "anneeNaissance": null,
      "photo": "",
      "familleId": null,
      "grandeFamilleId": "jouenang",
      "jourNaissance": 14,
      "rangNaissance": null
    },
    {
      "id": "jean-lebel-enfant-1",
      "prenom": "Nélaine",
      "nom": "Menzefo",
      "sexe": "F",
      "moisNaissance": 11,
      "anneeNaissance": null,
      "photo": "",
      "familleId": "famille-jean-lebel-jean-lebel-epouse",
      "grandeFamilleId": "jouenang",
      "jourNaissance": 19,
      "rangNaissance": 1
    },
    {
      "id": "jean-lebel-enfant-2",
      "prenom": "Wilson",
      "nom": "Ketcheuzeu",
      "sexe": "M",
      "moisNaissance": 5,
      "anneeNaissance": null,
      "photo": "",
      "familleId": "famille-jean-lebel-jean-lebel-epouse",
      "grandeFamilleId": "jouenang",
      "rangNaissance": 2,
      "jourNaissance": 9
    },
    {
      "id": "jean-lebel-enfant-3",
      "prenom": "Johanna",
      "nom": "Ngopnang",
      "sexe": "F",
      "moisNaissance": 4,
      "anneeNaissance": null,
      "photo": "",
      "familleId": "famille-jean-lebel-jean-lebel-epouse",
      "grandeFamilleId": "jouenang",
      "rangNaissance": 3,
      "jourNaissance": 26
    },
    {
      "id": "berthine",
      "prenom": "Berthine",
      "nom": "Tchatchouang",
      "sexe": "F",
      "moisNaissance": 7,
      "anneeNaissance": null,
      "photo": "photos/berthine.jpeg",
      "familleId": "famille-abel-martine",
      "grandeFamilleId": "jouenang",
      "jourNaissance": 4,
      "rangNaissance": 3
    },
    {
      "id": "berthine-epoux",
      "prenom": "Joseph",
      "nom": "Fokoua",
      "sexe": "M",
      "moisNaissance": 3,
      "anneeNaissance": null,
      "photo": "",
      "familleId": null,
      "grandeFamilleId": "jouenang",
      "jourNaissance": 25,
      "rangNaissance": null
    },
    {
      "id": "berthine-enfant-1",
      "prenom": "Kevin",
      "nom": "Fotso",
      "sexe": "M",
      "moisNaissance": 8,
      "anneeNaissance": null,
      "photo": "",
      "familleId": "famille-berthine-epoux-berthine",
      "grandeFamilleId": "jouenang",
      "rangNaissance": 1,
      "jourNaissance": 15
    },
    {
      "id": "berthine-enfant-2",
      "prenom": "Marlene",
      "nom": "Massudom",
      "sexe": "F",
      "moisNaissance": 1,
      "anneeNaissance": null,
      "photo": "",
      "familleId": "famille-berthine-epoux-berthine",
      "grandeFamilleId": "jouenang",
      "jourNaissance": 7,
      "rangNaissance": 2
    },
    {
      "id": "berthine-enfant-3",
      "prenom": "Guilene",
      "nom": "Menzefo",
      "sexe": "F",
      "moisNaissance": 1,
      "anneeNaissance": null,
      "photo": "",
      "familleId": "famille-berthine-epoux-berthine",
      "grandeFamilleId": "jouenang",
      "rangNaissance": 3,
      "jourNaissance": 5
    },
    {
      "id": "dagobert",
      "prenom": "Dagobert",
      "nom": "Djapou",
      "sexe": "M",
      "moisNaissance": 10,
      "anneeNaissance": null,
      "photo": "photos/dagobert-djapou.jpg",
      "familleId": "famille-abel-martine",
      "grandeFamilleId": "jouenang",
      "jourNaissance": 16,
      "rangNaissance": 4
    },
    {
      "id": "dagobert-epouse",
      "prenom": "Laure Hélène",
      "nom": "Podjie Woupo",
      "sexe": "F",
      "moisNaissance": 7,
      "anneeNaissance": null,
      "photo": "photos/laure-podjie.jpg",
      "familleId": null,
      "grandeFamilleId": "jouenang",
      "jourNaissance": 5,
      "rangNaissance": null
    },
    {
      "id": "dagobert-enfant-1",
      "prenom": "Grâce Olive",
      "nom": "Menzefo",
      "sexe": "F",
      "moisNaissance": 7,
      "anneeNaissance": null,
      "photo": "photos/grace-olive-menzefo.jpg",
      "familleId": "famille-dagobert-dagobert-epouse",
      "grandeFamilleId": "jouenang",
      "jourNaissance": 12,
      "rangNaissance": 1
    },
    {
      "id": "dagobert-enfant-2",
      "prenom": "Anne Lea",
      "nom": "Tchopkam",
      "sexe": "F",
      "moisNaissance": 11,
      "anneeNaissance": null,
      "photo": "photos/anne-lea-djapou.jpg",
      "familleId": "famille-dagobert-dagobert-epouse",
      "grandeFamilleId": "jouenang",
      "jourNaissance": 7,
      "rangNaissance": 2
    },
    {
      "id": "claude",
      "prenom": "Claude",
      "nom": "Djinang",
      "sexe": "M",
      "moisNaissance": 8,
      "anneeNaissance": null,
      "photo": "photos/claude.jpeg",
      "familleId": "famille-abel-martine",
      "grandeFamilleId": "jouenang",
      "jourNaissance": 12,
      "rangNaissance": 5
    },
    {
      "id": "claude-epouse",
      "prenom": "Jeanine",
      "nom": "Tchapdie",
      "sexe": "F",
      "moisNaissance": 2,
      "anneeNaissance": null,
      "photo": "",
      "familleId": null,
      "grandeFamilleId": "jouenang",
      "jourNaissance": 13,
      "rangNaissance": null
    },
    {
      "id": "claude-enfant-1",
      "prenom": "Stephan Karen",
      "nom": "Miyo",
      "sexe": "M",
      "moisNaissance": 5,
      "anneeNaissance": null,
      "photo": "",
      "familleId": "famille-claude-claude-epouse",
      "grandeFamilleId": "jouenang",
      "rangNaissance": 1,
      "jourNaissance": 15
    },
    {
      "id": "claude-enfant-2",
      "prenom": "Pharel Valery",
      "nom": "Tankoua",
      "sexe": "M",
      "moisNaissance": 2,
      "anneeNaissance": null,
      "photo": "",
      "familleId": "famille-claude-claude-epouse",
      "grandeFamilleId": "jouenang",
      "rangNaissance": 2,
      "jourNaissance": 7
    },
    {
      "id": "claude-enfant-3",
      "prenom": "Sorel Carine",
      "nom": "Menzefo",
      "sexe": "F",
      "moisNaissance": 7,
      "anneeNaissance": null,
      "photo": "",
      "familleId": "famille-claude-claude-epouse",
      "grandeFamilleId": "jouenang",
      "rangNaissance": 3,
      "jourNaissance": 31
    },
    {
      "id": "claude-enfant-4",
      "prenom": "Allan Chris",
      "nom": "Djinang",
      "sexe": "M",
      "moisNaissance": 4,
      "anneeNaissance": null,
      "photo": "",
      "familleId": "famille-claude-claude-epouse",
      "grandeFamilleId": "jouenang",
      "rangNaissance": 4,
      "jourNaissance": 28
    },
    {
      "id": "jules",
      "prenom": "Jules",
      "nom": "Komguep",
      "sexe": "M",
      "moisNaissance": 9,
      "anneeNaissance": null,
      "photo": "photos/jules-komguep.JPG",
      "familleId": "famille-abel-martine",
      "grandeFamilleId": "jouenang",
      "jourNaissance": 8,
      "rangNaissance": 6
    },
    {
      "id": "jules-epouse",
      "prenom": "Claire",
      "nom": "Ngantcha",
      "sexe": "F",
      "moisNaissance": 1,
      "anneeNaissance": null,
      "photo": "photos/claire-ngantcha.jpg",
      "familleId": "tchonkap",
      "grandeFamilleId": "jouenang",
      "jourNaissance": 12,
      "rangNaissance": null
    },
    {
      "id": "jules-enfant-1",
      "prenom": "Steve",
      "nom": "Jouenang",
      "sexe": "M",
      "moisNaissance": 10,
      "anneeNaissance": null,
      "photo": "photos/steve-jouenang.jpg",
      "familleId": "famille-jules-jules-epouse",
      "grandeFamilleId": "jouenang",
      "jourNaissance": 17,
      "rangNaissance": 1
    },
    {
      "id": "jules-enfant-2",
      "prenom": "Ornela",
      "nom": "Yimga",
      "sexe": "F",
      "moisNaissance": 6,
      "anneeNaissance": null,
      "photo": "",
      "familleId": "famille-jules-jules-epouse",
      "grandeFamilleId": "jouenang",
      "rangNaissance": 2,
      "jourNaissance": 22
    },
    {
      "id": "jules-enfant-3",
      "prenom": "Ivika",
      "nom": "Tchatchouang",
      "sexe": "F",
      "moisNaissance": 8,
      "anneeNaissance": null,
      "photo": "",
      "familleId": "famille-jules-jules-epouse",
      "grandeFamilleId": "jouenang",
      "rangNaissance": 3,
      "jourNaissance": 22
    },
    {
      "id": "jules-enfant-4",
      "prenom": "Lorick",
      "nom": "Komguep-Tchonkap",
      "sexe": "M",
      "moisNaissance": 5,
      "anneeNaissance": null,
      "photo": "photos/lorick-komguep-tchonkap.jpg",
      "familleId": "famille-jules-jules-epouse",
      "grandeFamilleId": "jouenang",
      "rangNaissance": 4,
      "jourNaissance": 18
    },
    {
      "id": "cecile",
      "prenom": "Cécile",
      "nom": "Miyou",
      "sexe": "F",
      "moisNaissance": 6,
      "anneeNaissance": null,
      "photo": "photos/cecile-miyou.jpg",
      "familleId": "famille-koutchadjio",
      "grandeFamilleId": "jouenang",
      "jourNaissance": 13,
      "rangNaissance": 3
    },
    {
      "id": "alain",
      "prenom": "Alain",
      "nom": "Tchiemegne",
      "sexe": "M",
      "moisNaissance": 8,
      "anneeNaissance": null,
      "photo": "photos/alain.jpeg",
      "familleId": "famille-abel-cecile",
      "grandeFamilleId": "jouenang",
      "jourNaissance": 29,
      "rangNaissance": 1
    },
    {
      "id": "valerie",
      "prenom": "Valérie",
      "nom": "Nagfack",
      "sexe": "F",
      "moisNaissance": 10,
      "anneeNaissance": null,
      "photo": "photos/valerie-nagfack.jpg",
      "familleId": "famille-abel-cecile",
      "grandeFamilleId": "jouenang",
      "jourNaissance": 6,
      "rangNaissance": 2
    },
    {
      "id": "bertin",
      "prenom": "Bertin",
      "nom": "Poka'a",
      "sexe": "M",
      "moisNaissance": 1,
      "anneeNaissance": null,
      "photo": "photos/bertin.jpeg",
      "familleId": "famille-abel-cecile",
      "grandeFamilleId": "jouenang",
      "jourNaissance": 4,
      "rangNaissance": 3
    },
    {
      "id": "bertin-epouse",
      "prenom": "Gisèle Calverine",
      "nom": "Ngako",
      "sexe": "F",
      "moisNaissance": 3,
      "anneeNaissance": null,
      "photo": "photos/gisele-calverine-ngako.jpg",
      "familleId": null,
      "grandeFamilleId": "jouenang",
      "jourNaissance": 5,
      "rangNaissance": null
    },
    {
      "id": "bertin-enfant-1",
      "prenom": "Marc Gabriel",
      "nom": "Poka'a Nana",
      "sexe": "M",
      "moisNaissance": 8,
      "anneeNaissance": null,
      "photo": "photos/marc-gabriel-poka-a-nana.jpg",
      "familleId": "famille-bertin-bertin-epouse",
      "grandeFamilleId": "jouenang",
      "jourNaissance": 24,
      "rangNaissance": 3
    },
    {
      "id": "bertin-enfant-2",
      "prenom": "Abel Raphaël",
      "nom": "Poka'a Miyou",
      "sexe": "M",
      "moisNaissance": 7,
      "anneeNaissance": null,
      "photo": "photos/abel-raphael-poka-a-miyou.jpg",
      "familleId": "famille-bertin-bertin-epouse",
      "grandeFamilleId": "jouenang",
      "jourNaissance": 24,
      "rangNaissance": 4
    },
    {
      "id": "bertin-enfant-3",
      "prenom": "David Michel",
      "nom": "Poka'a Fokwa",
      "sexe": "M",
      "moisNaissance": 5,
      "anneeNaissance": null,
      "photo": "photos/david-michel-poka-a-fokwa.jpg",
      "familleId": "famille-bertin-bertin-epouse",
      "grandeFamilleId": "jouenang",
      "jourNaissance": 20,
      "rangNaissance": 2
    },
    {
      "id": "nadege",
      "prenom": "Nadège",
      "nom": "Kouokam",
      "sexe": "F",
      "moisNaissance": 3,
      "anneeNaissance": null,
      "photo": "photos/nadege-kouokam.jpg",
      "familleId": "famille-abel-cecile",
      "grandeFamilleId": "jouenang",
      "jourNaissance": 27,
      "rangNaissance": 4
    },
    {
      "id": "nadege-epoux",
      "prenom": "Lucas",
      "nom": "Mouafo",
      "sexe": "M",
      "moisNaissance": 8,
      "anneeNaissance": null,
      "photo": "photos/lucas-mouafo.jpg",
      "familleId": null,
      "grandeFamilleId": "jouenang",
      "jourNaissance": 25,
      "rangNaissance": null
    },
    {
      "id": "nadege-enfant-1",
      "prenom": "Phanuel",
      "nom": "Lontsi Mouafo",
      "sexe": "M",
      "moisNaissance": 7,
      "anneeNaissance": null,
      "photo": "photos/phanuel-lontsi-mouafo.jpg",
      "familleId": "famille-nadege-epoux-nadege",
      "grandeFamilleId": "jouenang",
      "jourNaissance": 16,
      "rangNaissance": 2
    },
    {
      "id": "nadege-enfant-2",
      "prenom": "Cécile Laure",
      "nom": "Ngopnang Mouafo",
      "sexe": "F",
      "moisNaissance": 9,
      "anneeNaissance": null,
      "photo": "photos/cecile-laure-ngopnang-mouafo.jpg",
      "familleId": "famille-nadege-epoux-nadege",
      "grandeFamilleId": "jouenang",
      "jourNaissance": 11,
      "rangNaissance": 1
    },
    {
      "id": "nadege-enfant-3",
      "prenom": "Delphine Archange",
      "nom": "Tchinda Mouafo",
      "sexe": "F",
      "moisNaissance": 1,
      "anneeNaissance": null,
      "photo": "photos/delphine-archange-tchinda-mouafo.jpg",
      "familleId": "famille-nadege-epoux-nadege",
      "grandeFamilleId": "jouenang",
      "jourNaissance": 10,
      "rangNaissance": 3
    },
    {
      "id": "nadege-enfant-4",
      "prenom": "Christ Abel",
      "nom": "Djimeli Mouafo",
      "sexe": "M",
      "moisNaissance": 1,
      "anneeNaissance": null,
      "photo": "photos/christ-abel-djimeli-mouafo.jpg",
      "familleId": "famille-nadege-epoux-nadege",
      "grandeFamilleId": "jouenang",
      "jourNaissance": 26,
      "rangNaissance": 4
    },
    {
      "id": "sylvia",
      "prenom": "Sylvia",
      "nom": "Sotche",
      "sexe": "F",
      "moisNaissance": 3,
      "anneeNaissance": null,
      "photo": "photos/sylvia-sotche.jpg",
      "familleId": "famille-abel-cecile",
      "grandeFamilleId": "jouenang",
      "jourNaissance": 11,
      "rangNaissance": 5
    },
    {
      "id": "alvine",
      "prenom": "Alvine",
      "nom": "Guenang",
      "sexe": "F",
      "moisNaissance": 9,
      "anneeNaissance": null,
      "photo": "photos/alvine-guenang.jpg",
      "familleId": "famille-abel-cecile",
      "grandeFamilleId": "jouenang",
      "jourNaissance": 1,
      "rangNaissance": 6
    },
    {
      "id": "alvine-epoux",
      "prenom": "Époux d'Alvine",
      "nom": "",
      "sexe": "M",
      "moisNaissance": null,
      "anneeNaissance": null,
      "photo": "",
      "familleId": null,
      "grandeFamilleId": "jouenang",
      "masque": true
    },
    {
      "id": "alvine-enfant-1",
      "prenom": "Franck-Patrick",
      "nom": "Komguep",
      "sexe": "M",
      "moisNaissance": 8,
      "anneeNaissance": null,
      "photo": "photos/franck-patrick-komguep.jpg",
      "familleId": "famille-alvine-epoux-alvine",
      "grandeFamilleId": "jouenang",
      "jourNaissance": 26,
      "rangNaissance": null
    },
    {
      "id": "pascal-yves-tidjouon",
      "prenom": "Pascal Yves",
      "nom": "Tidjouon",
      "sexe": "M",
      "moisNaissance": 4,
      "anneeNaissance": null,
      "jourNaissance": 27,
      "rangNaissance": 1,
      "photo": "photos/pascal-yves-tidjouon.jpg",
      "familleId": null,
      "grandeFamilleId": "djampou"
    },
    {
      "id": "louise-pelagie-tchopkam-djampou",
      "prenom": "Louise Pélagie",
      "nom": "Tchopkam Djampou",
      "sexe": "F",
      "moisNaissance": 3,
      "anneeNaissance": null,
      "jourNaissance": 14,
      "rangNaissance": 3,
      "photo": "photos/louise-pelagie-tchopkam-djampou.jpg",
      "familleId": "djampou",
      "grandeFamilleId": "djampou"
    },
    {
      "id": "arthur-tidjouon-ngopnang",
      "prenom": "Arthur",
      "nom": "Tidjouon Ngopnang",
      "sexe": "M",
      "moisNaissance": 2,
      "anneeNaissance": null,
      "jourNaissance": 20,
      "rangNaissance": 1,
      "photo": "photos/arthur-tidjouon-ngopnang.jpg",
      "familleId": "tidjouon",
      "grandeFamilleId": "djampou"
    },
    {
      "id": "joyce-yvana-tidououn-nguikou",
      "prenom": "Joyce Yvana",
      "nom": "Tidjouon Nguikou",
      "sexe": "F",
      "moisNaissance": 5,
      "anneeNaissance": null,
      "jourNaissance": 29,
      "rangNaissance": 2,
      "photo": "photos/joyce-yvana-tidjouon-nguikou.jpg",
      "familleId": "tidjouon",
      "grandeFamilleId": "djampou"
    },
    {
      "id": "ange-bryan-tidjouon",
      "prenom": "Ange Bryan",
      "nom": "Tidjouon",
      "sexe": "M",
      "moisNaissance": 4,
      "anneeNaissance": null,
      "jourNaissance": 11,
      "rangNaissance": 3,
      "photo": "photos/ange-bryan-tidjouon.jpg",
      "familleId": "tidjouon",
      "grandeFamilleId": "djampou"
    },
    {
      "id": "theodora-ange-noel-nguekam-tchamabong",
      "prenom": "Theodora Ange Noël",
      "nom": "Nguekam Tchamabong",
      "sexe": "F",
      "moisNaissance": 12,
      "anneeNaissance": null,
      "jourNaissance": 25,
      "rangNaissance": 2,
      "photo": "photos/theodora-ange-noel-nguekam-tchamabong.jpg",
      "familleId": "famille-nguekam-2",
      "grandeFamilleId": "tchoungang"
    },
    {
      "id": "serge-valery-atangana-mbanga",
      "prenom": "Serge Valery",
      "nom": "Atangana Mbanga",
      "sexe": "M",
      "moisNaissance": 3,
      "anneeNaissance": null,
      "jourNaissance": 29,
      "rangNaissance": null,
      "photo": "photos/serge-valery-atangana-mbanga.jpg",
      "familleId": null,
      "grandeFamilleId": "tchoungang"
    },
    {
      "id": "enzo-herman-taked-tchoungang-kamdoum",
      "prenom": "Enzo Herman",
      "nom": "Taked Tchoungang Kamdoum",
      "sexe": "M",
      "moisNaissance": 1,
      "anneeNaissance": null,
      "jourNaissance": 1,
      "rangNaissance": 1,
      "photo": "photos/enzo-herman-taked-tchoungang-kamdoum.jpg",
      "familleId": "atangana",
      "grandeFamilleId": "tchoungang"
    },
    {
      "id": "raphael-sylvain-atangana-mbanga-ngopnang",
      "prenom": "Raphaël Sylvain",
      "nom": "Atangana Mbanga Ngopnang",
      "sexe": "M",
      "moisNaissance": 1,
      "anneeNaissance": null,
      "jourNaissance": 12,
      "rangNaissance": null,
      "photo": "photos/raphael-sylvain-atangana-mbanga-ngopnang.jpg",
      "familleId": "atangana",
      "grandeFamilleId": "tchoungang"
    },
    {
      "id": "zenabou-anne-atangana-mbanga",
      "prenom": "Zenabou Anne",
      "nom": "Atangana Mbanga",
      "sexe": "F",
      "moisNaissance": 7,
      "anneeNaissance": null,
      "jourNaissance": 30,
      "rangNaissance": null,
      "photo": "photos/zenabou-anne-atangana-mbanga.jpg",
      "familleId": "atangana",
      "grandeFamilleId": "tchoungang"
    },
    {
      "id": "lebel-tchiedjop",
      "prenom": "Lebel",
      "nom": "Tchiedjop",
      "sexe": "M",
      "moisNaissance": null,
      "anneeNaissance": null,
      "jourNaissance": null,
      "rangNaissance": null,
      "photo": "",
      "familleId": "kapnang",
      "grandeFamilleId": "jouenang",
      "decede": true
    },
    {
      "id": "julienne-djomo",
      "prenom": "Julienne",
      "nom": "Djomo",
      "sexe": "F",
      "moisNaissance": 1,
      "anneeNaissance": 1914,
      "jourNaissance": null,
      "rangNaissance": null,
      "photo": "",
      "familleId": "nagmegne",
      "grandeFamilleId": "jouenang",
      "decede": true,
      "moisDeces": 4,
      "anneeDeces": 1985
    },
    {
      "id": "webo-koutchadjio",
      "prenom": "Poka'a",
      "nom": "Koutchadjio",
      "sexe": "M",
      "moisNaissance": null,
      "anneeNaissance": null,
      "jourNaissance": null,
      "rangNaissance": null,
      "photo": "",
      "familleId": "famille-kouonang",
      "grandeFamilleId": "jouenang",
      "decede": true,
      "anneeDeces": 1996
    },
    {
      "id": "emilienne-sotche",
      "prenom": "Marthe",
      "nom": "Sotche",
      "sexe": "F",
      "moisNaissance": null,
      "anneeNaissance": null,
      "jourNaissance": null,
      "rangNaissance": null,
      "photo": "",
      "familleId": "famille-webo-sawag",
      "grandeFamilleId": "jouenang",
      "decede": true,
      "anneeDeces": 1992
    },
    {
      "id": "josephine-miyo",
      "prenom": "Joséphine",
      "nom": "Miyo",
      "sexe": "F",
      "moisNaissance": null,
      "anneeNaissance": null,
      "jourNaissance": null,
      "rangNaissance": null,
      "photo": "",
      "familleId": "famille-notsa-a",
      "grandeFamilleId": "jouenang",
      "decede": true
    },
    {
      "id": "abel-guepning",
      "prenom": "Abel",
      "nom": "Nguepnin",
      "sexe": "M",
      "moisNaissance": null,
      "anneeNaissance": 1889,
      "jourNaissance": null,
      "rangNaissance": null,
      "photo": "photos/abel-nguepnin.jpg",
      "familleId": "famille-djapou-aieul",
      "grandeFamilleId": "jouenang",
      "decede": true,
      "moisDeces": 1,
      "anneeDeces": 1965
    },
    {
      "id": "thomas-djampou",
      "prenom": "Thomas",
      "nom": "Djampou",
      "sexe": "M",
      "moisNaissance": 7,
      "anneeNaissance": null,
      "jourNaissance": 20,
      "rangNaissance": null,
      "photo": "photos/thomas-djampou.jpg",
      "familleId": null,
      "grandeFamilleId": "djampou"
    },
    {
      "id": "jeanne-noumboue",
      "prenom": "Jeanne",
      "nom": "Noumboue",
      "sexe": "F",
      "moisNaissance": 2,
      "anneeNaissance": null,
      "jourNaissance": 20,
      "rangNaissance": null,
      "photo": "photos/jeanne-noumboue.jpg",
      "familleId": null,
      "grandeFamilleId": "djampou"
    },
    {
      "id": "lydie-wandji",
      "prenom": "Lydiane",
      "nom": "Wandji Chana",
      "sexe": "F",
      "moisNaissance": 9,
      "anneeNaissance": null,
      "jourNaissance": 22,
      "rangNaissance": null,
      "photo": "",
      "familleId": "tchoungang",
      "grandeFamilleId": "tchoungang"
    },
    {
      "id": "crepin-nguepdjop",
      "prenom": "Crépin",
      "nom": "Nguepdjop",
      "sexe": "M",
      "jourNaissance": 25,
      "moisNaissance": 10,
      "anneeNaissance": null,
      "rangNaissance": null,
      "photo": "photos/crepin-nguepdjop.jpg",
      "familleId": null,
      "grandeFamilleId": "jouenang"
    },
    {
      "id": "regine-djouonang",
      "prenom": "Régine",
      "nom": "Djouonang",
      "sexe": "F",
      "jourNaissance": 29,
      "moisNaissance": 8,
      "anneeNaissance": null,
      "rangNaissance": null,
      "photo": "photos/regine-djouonang.jpg",
      "familleId": "famille-kouonang-2",
      "grandeFamilleId": "jouenang"
    },
    {
      "id": "nguepdjop-enfant-1",
      "prenom": "Joëlle",
      "nom": "Nguepdjop",
      "sexe": "F",
      "jourNaissance": 14,
      "moisNaissance": 9,
      "anneeNaissance": null,
      "rangNaissance": 1,
      "photo": "photos/joelle-nguepdjop.jpg",
      "familleId": "famille-nguepdjop",
      "grandeFamilleId": "jouenang"
    },
    {
      "id": "nguepdjop-enfant-2",
      "prenom": "Abiel",
      "nom": "Nguepdjop",
      "sexe": "M",
      "jourNaissance": 6,
      "moisNaissance": 10,
      "anneeNaissance": null,
      "rangNaissance": 2,
      "photo": "photos/abiel-nguepdjop.jpg",
      "familleId": "famille-nguepdjop",
      "grandeFamilleId": "jouenang"
    },
    {
      "id": "nguepdjop-enfant-3",
      "prenom": "Anaëlle",
      "nom": "Nguepdjop Kouonang",
      "sexe": "F",
      "jourNaissance": 3,
      "moisNaissance": 6,
      "anneeNaissance": null,
      "rangNaissance": 3,
      "photo": "photos/anaelle-nguepdjop-kouonang.jpg",
      "familleId": "famille-nguepdjop",
      "grandeFamilleId": "jouenang"
    },
    {
      "id": "nguepdjop-enfant-4",
      "prenom": "Josepha",
      "nom": "Nguepdjop Pomegne",
      "sexe": "F",
      "jourNaissance": 6,
      "moisNaissance": 6,
      "anneeNaissance": null,
      "rangNaissance": 4,
      "photo": "photos/josepha-nguepdjop-pomegne.jpg",
      "familleId": "famille-nguepdjop",
      "grandeFamilleId": "jouenang"
    },
    {
      "id": "maria",
      "prenom": "Maria",
      "nom": "",
      "sexe": "F",
      "moisNaissance": null,
      "anneeNaissance": null,
      "jourNaissance": null,
      "rangNaissance": null,
      "photo": "",
      "familleId": null,
      "grandeFamilleId": "jouenang"
    },
    {
      "id": "kylian-fotso",
      "prenom": "Kylian",
      "nom": "Fotso",
      "sexe": "M",
      "moisNaissance": 3,
      "anneeNaissance": null,
      "jourNaissance": 25,
      "rangNaissance": null,
      "photo": "",
      "familleId": "famille-fotso",
      "grandeFamilleId": "jouenang"
    },
    {
      "id": "chloe-fotso",
      "prenom": "Chloé",
      "nom": "Fotso",
      "sexe": "F",
      "moisNaissance": 9,
      "anneeNaissance": null,
      "jourNaissance": 3,
      "rangNaissance": null,
      "photo": "",
      "familleId": "famille-fotso",
      "grandeFamilleId": "jouenang"
    },
    {
      "id": "agnes-edzimbi",
      "prenom": "Agnès",
      "nom": "Edzimbi",
      "sexe": "F",
      "moisNaissance": 7,
      "anneeNaissance": null,
      "jourNaissance": 31,
      "rangNaissance": null,
      "photo": "",
      "familleId": null,
      "grandeFamilleId": "jouenang"
    },
    {
      "id": "nathanael-piegouong-kamnang",
      "prenom": "Nathanaël",
      "nom": "Piegouong Kamnang",
      "sexe": "M",
      "moisNaissance": 4,
      "anneeNaissance": null,
      "jourNaissance": 26,
      "rangNaissance": null,
      "photo": "",
      "familleId": "famille-piegouong",
      "grandeFamilleId": "jouenang"
    },
    {
      "id": "regine-blanche",
      "prenom": "Régine",
      "nom": "Tchouantche Possi",
      "sexe": "F",
      "moisNaissance": 3,
      "anneeNaissance": null,
      "jourNaissance": 19,
      "rangNaissance": null,
      "photo": "photos/regine-tchouantche-possi.jpg",
      "familleId": null,
      "grandeFamilleId": "jouenang"
    },
    {
      "id": "joseph-chana",
      "prenom": "Joseph",
      "nom": "Chana",
      "sexe": "M",
      "moisNaissance": null,
      "anneeNaissance": null,
      "jourNaissance": null,
      "rangNaissance": null,
      "photo": "photos/joseph-chana.jpg",
      "familleId": null,
      "grandeFamilleId": "tchoungang",
      "decede": true,
      "anneeDeces": 2017
    },
    {
      "id": "catherine-tchoungang",
      "prenom": "Cathérine",
      "nom": "Tchoungang",
      "sexe": "F",
      "moisNaissance": null,
      "anneeNaissance": null,
      "jourNaissance": null,
      "rangNaissance": null,
      "photo": "photos/catherine-tchoungang.jpg",
      "familleId": "famille-tenkam",
      "grandeFamilleId": "tchoungang",
      "decede": true,
      "moisDeces": 10,
      "anneeDeces": 2015
    },
    {
      "id": "osee-tchonkap",
      "prenom": "Osée",
      "nom": "Tchonkap",
      "sexe": "M",
      "moisNaissance": null,
      "anneeNaissance": 1936,
      "jourNaissance": null,
      "rangNaissance": null,
      "photo": "",
      "familleId": null,
      "grandeFamilleId": null,
      "decede": true,
      "jourDeces": 18,
      "moisDeces": 9,
      "anneeDeces": 1998
    },
    {
      "id": "marcelline-yimga",
      "prenom": "Marcelline",
      "nom": "Yimga",
      "sexe": "F",
      "moisNaissance": null,
      "anneeNaissance": 1940,
      "jourNaissance": null,
      "rangNaissance": null,
      "photo": "",
      "familleId": null,
      "grandeFamilleId": null,
      "decede": true,
      "moisDeces": 11,
      "anneeDeces": 2023
    },
    {
      "id": "papa-kapnang",
      "prenom": "Papa",
      "nom": "Kapnang",
      "sexe": "M",
      "moisNaissance": null,
      "anneeNaissance": null,
      "jourNaissance": null,
      "rangNaissance": null,
      "photo": "",
      "familleId": null,
      "grandeFamilleId": "jouenang",
      "decede": true
    },
    {
      "id": "maman-guenang",
      "prenom": "Maman",
      "nom": "Guenang",
      "sexe": "F",
      "moisNaissance": null,
      "anneeNaissance": null,
      "jourNaissance": null,
      "decede": true,
      "rangNaissance": null,
      "photo": "",
      "familleId": null,
      "grandeFamilleId": "jouenang"
    },
    {
      "id": "papa-nagmegne",
      "prenom": "Papa",
      "nom": "Nagmegne",
      "sexe": "M",
      "moisNaissance": null,
      "anneeNaissance": null,
      "jourNaissance": null,
      "decede": true,
      "rangNaissance": null,
      "photo": "",
      "familleId": null,
      "grandeFamilleId": "jouenang"
    },
    {
      "id": "maman-kaptchouang",
      "prenom": "Maman",
      "nom": "Kaptchouang",
      "sexe": "F",
      "moisNaissance": null,
      "anneeNaissance": null,
      "jourNaissance": null,
      "decede": true,
      "rangNaissance": null,
      "photo": "",
      "familleId": null,
      "grandeFamilleId": "jouenang"
    },
    {
      "id": "papa-kouonang",
      "prenom": "Papa",
      "nom": "Kouonang",
      "sexe": "M",
      "moisNaissance": null,
      "anneeNaissance": null,
      "jourNaissance": null,
      "decede": true,
      "rangNaissance": null,
      "photo": "",
      "familleId": null,
      "grandeFamilleId": "jouenang"
    },
    {
      "id": "maman-meliedje",
      "prenom": "Maman",
      "nom": "Meliedje",
      "sexe": "F",
      "moisNaissance": null,
      "anneeNaissance": null,
      "jourNaissance": null,
      "decede": true,
      "rangNaissance": null,
      "photo": "",
      "familleId": null,
      "grandeFamilleId": "jouenang"
    },
    {
      "id": "papa-webo-sawag",
      "prenom": "Papa",
      "nom": "Webo Sawag",
      "sexe": "M",
      "moisNaissance": null,
      "anneeNaissance": null,
      "jourNaissance": null,
      "decede": true,
      "rangNaissance": null,
      "photo": "",
      "familleId": null,
      "grandeFamilleId": "jouenang"
    },
    {
      "id": "maman-komguep",
      "prenom": "Maman",
      "nom": "Komguep",
      "sexe": "F",
      "moisNaissance": null,
      "anneeNaissance": null,
      "jourNaissance": null,
      "decede": true,
      "rangNaissance": null,
      "photo": "",
      "familleId": null,
      "grandeFamilleId": "jouenang"
    },
    {
      "id": "papa-djapou",
      "prenom": "Papa",
      "nom": "Djapou",
      "sexe": "M",
      "moisNaissance": null,
      "anneeNaissance": null,
      "jourNaissance": null,
      "decede": true,
      "rangNaissance": null,
      "photo": "",
      "familleId": null,
      "grandeFamilleId": "jouenang"
    },
    {
      "id": "maman-ndap",
      "prenom": "Maman",
      "nom": "Ndap",
      "sexe": "F",
      "moisNaissance": null,
      "anneeNaissance": null,
      "jourNaissance": null,
      "decede": true,
      "rangNaissance": null,
      "photo": "",
      "familleId": null,
      "grandeFamilleId": "jouenang"
    },
    {
      "id": "papa-notsa-a",
      "prenom": "Papa",
      "nom": "Notsa'a",
      "sexe": "M",
      "moisNaissance": null,
      "anneeNaissance": null,
      "jourNaissance": null,
      "decede": true,
      "rangNaissance": null,
      "photo": "",
      "familleId": null,
      "grandeFamilleId": "jouenang"
    },
    {
      "id": "maman-tchatchouang-meliedje",
      "prenom": "Maman",
      "nom": "Tchatchouang Meliedje",
      "sexe": "F",
      "moisNaissance": null,
      "anneeNaissance": null,
      "jourNaissance": null,
      "decede": true,
      "rangNaissance": null,
      "photo": "",
      "familleId": null,
      "grandeFamilleId": "jouenang"
    },
    {
      "id": "joseph-fotso",
      "prenom": "Joseph",
      "nom": "Fotso",
      "sexe": "M",
      "moisNaissance": null,
      "anneeNaissance": null,
      "jourNaissance": null,
      "decede": true,
      "rangNaissance": 1,
      "photo": "",
      "familleId": "famille-guepning",
      "grandeFamilleId": "jouenang"
    },
    {
      "id": "justin-komegne",
      "prenom": "Justin",
      "nom": "Komegne",
      "sexe": "M",
      "moisNaissance": null,
      "anneeNaissance": null,
      "jourNaissance": null,
      "decede": true,
      "anneeDeces": 2009,
      "rangNaissance": 3,
      "photo": "",
      "familleId": "famille-guepning",
      "grandeFamilleId": "jouenang"
    },
    {
      "id": "anasthasie-chimi",
      "prenom": "Anasthasie",
      "nom": "Chimi",
      "sexe": "F",
      "moisNaissance": 6,
      "anneeNaissance": null,
      "jourNaissance": 18,
      "rangNaissance": 4,
      "photo": "",
      "familleId": "famille-guepning",
      "grandeFamilleId": "jouenang"
    },
    {
      "id": "papa-augustin",
      "prenom": "Papa",
      "nom": "Augustin",
      "sexe": "M",
      "moisNaissance": null,
      "anneeNaissance": null,
      "jourNaissance": null,
      "decede": true,
      "rangNaissance": null,
      "photo": "",
      "familleId": "famille-guepning",
      "grandeFamilleId": "jouenang"
    },
    {
      "id": "maman-madefo",
      "prenom": "Maman",
      "nom": "Madefo",
      "sexe": "F",
      "moisNaissance": null,
      "anneeNaissance": null,
      "jourNaissance": null,
      "decede": true,
      "rangNaissance": null,
      "photo": "",
      "familleId": "famille-djapou-aieul",
      "grandeFamilleId": "jouenang"
    },
    {
      "id": "papa-defo",
      "prenom": "Papa",
      "nom": "Defo",
      "sexe": "M",
      "moisNaissance": null,
      "anneeNaissance": null,
      "jourNaissance": null,
      "decede": true,
      "rangNaissance": null,
      "photo": "",
      "familleId": "famille-djapou-aieul",
      "grandeFamilleId": "jouenang"
    },
    {
      "id": "maurice-neghe",
      "prenom": "Maurice",
      "nom": "Neghe",
      "sexe": "M",
      "moisNaissance": null,
      "anneeNaissance": null,
      "jourNaissance": null,
      "decede": true,
      "rangNaissance": null,
      "photo": "",
      "familleId": "famille-djapou-aieul",
      "grandeFamilleId": "jouenang"
    },
    {
      "id": "therese-chimi",
      "prenom": "Thérèse",
      "nom": "Chimi",
      "sexe": "F",
      "moisNaissance": null,
      "anneeNaissance": null,
      "jourNaissance": null,
      "decede": true,
      "rangNaissance": null,
      "photo": "",
      "familleId": "famille-notsa-a",
      "grandeFamilleId": "jouenang"
    },
    {
      "id": "papa-po-o-tchedhe",
      "prenom": "Papa Po'o",
      "nom": "Tchedhe",
      "sexe": "M",
      "moisNaissance": null,
      "anneeNaissance": null,
      "jourNaissance": null,
      "decede": true,
      "rangNaissance": null,
      "photo": "",
      "familleId": "famille-notsa-a",
      "grandeFamilleId": "jouenang"
    },
    {
      "id": "eden-alain-miyou-mouafo",
      "prenom": "Eden Alain",
      "nom": "Miyou Mouafo",
      "sexe": "M",
      "moisNaissance": 1,
      "anneeNaissance": null,
      "jourNaissance": 15,
      "rangNaissance": null,
      "photo": "photos/eden-alain-miyou-mouafo.jpg",
      "familleId": "famille-nadege-epoux-nadege",
      "grandeFamilleId": "jouenang"
    },
    {
      "id": "gaetan-nkuemo-sielalie",
      "prenom": "Gaetan",
      "nom": "Nkuemo Sielalie",
      "sexe": "M",
      "moisNaissance": 5,
      "anneeNaissance": null,
      "jourNaissance": 13,
      "rangNaissance": null,
      "photo": "photos/gaetan-nkuemo-sielalie.jpg",
      "familleId": null,
      "grandeFamilleId": "jouenang"
    },
    {
      "id": "maxime-beranger-tchangang-nsah",
      "prenom": "Maxime Béranger",
      "nom": "Tchangang Nsah",
      "sexe": "M",
      "moisNaissance": 9,
      "anneeNaissance": null,
      "jourNaissance": 27,
      "rangNaissance": null,
      "photo": "photos/maxime-beranger-tchangang-nsah.jpg",
      "familleId": "famille-nkuemo-sielalie",
      "grandeFamilleId": "jouenang"
    },
    {
      "id": "david-aime-kamnang",
      "prenom": "David Aimé",
      "nom": "Kamnang",
      "sexe": "M",
      "moisNaissance": 5,
      "anneeNaissance": null,
      "jourNaissance": 1,
      "rangNaissance": null,
      "photo": "photos/aime-david-kamnang.jpg",
      "familleId": "famille-nkuemo-sielalie",
      "grandeFamilleId": "jouenang"
    },
    {
      "id": "sidonie-claire-tchonang-djampou",
      "prenom": "Sidonie Claire",
      "nom": "Tchonang Djampou",
      "sexe": "F",
      "moisNaissance": 9,
      "anneeNaissance": null,
      "jourNaissance": 22,
      "rangNaissance": 1,
      "photo": "",
      "familleId": "djampou",
      "grandeFamilleId": "djampou"
    },
    {
      "id": "jules-bruno-tchewe-djampou",
      "prenom": "Jules Bruno",
      "nom": "Tchewe Djampou",
      "sexe": "M",
      "moisNaissance": null,
      "anneeNaissance": null,
      "jourNaissance": null,
      "rangNaissance": 2,
      "photo": "",
      "familleId": "djampou",
      "grandeFamilleId": "djampou"
    },
    {
      "id": "colette-desiree-fanhouo-djampou",
      "prenom": "Colette Désirée",
      "nom": "Fanhouo Djampou",
      "sexe": "F",
      "moisNaissance": null,
      "anneeNaissance": null,
      "jourNaissance": null,
      "rangNaissance": null,
      "photo": "",
      "familleId": "djampou",
      "grandeFamilleId": "djampou"
    },
    {
      "id": "michel-djongang",
      "prenom": "Michel",
      "nom": "Djongang",
      "sexe": "M",
      "moisNaissance": 2,
      "anneeNaissance": null,
      "jourNaissance": 22,
      "rangNaissance": null,
      "photo": "",
      "familleId": null,
      "grandeFamilleId": "djampou"
    },
    {
      "id": "stephanie-nzeusseu",
      "prenom": "Stephanie",
      "nom": "Nzeusseu",
      "sexe": "F",
      "moisNaissance": null,
      "anneeNaissance": null,
      "jourNaissance": null,
      "decede": true,
      "rangNaissance": 1,
      "photo": "",
      "familleId": "famille-djongang",
      "grandeFamilleId": "djampou"
    },
    {
      "id": "willy-martial-ngougou-djongang",
      "prenom": "Willy Martial",
      "nom": "Ngougou Djongang",
      "sexe": "M",
      "moisNaissance": 7,
      "anneeNaissance": null,
      "jourNaissance": 13,
      "rangNaissance": 2,
      "photo": "",
      "familleId": "famille-djongang",
      "grandeFamilleId": "djampou"
    },
    {
      "id": "ines-djongang",
      "prenom": "Ines",
      "nom": "Djongang",
      "sexe": "F",
      "moisNaissance": 5,
      "anneeNaissance": null,
      "jourNaissance": 10,
      "rangNaissance": 3,
      "photo": "",
      "familleId": "famille-djongang",
      "grandeFamilleId": "djampou"
    },
    {
      "id": "aurelle-kapnang-djongang",
      "prenom": "Aurelle",
      "nom": "Kapnang Djongang",
      "sexe": "F",
      "moisNaissance": 2,
      "anneeNaissance": null,
      "jourNaissance": 22,
      "rangNaissance": 4,
      "photo": "",
      "familleId": "famille-djongang",
      "grandeFamilleId": "djampou"
    },
    {
      "id": "franck-nanwou-djongang",
      "prenom": "Franck",
      "nom": "Nanwou Djongang",
      "sexe": "M",
      "moisNaissance": 3,
      "anneeNaissance": null,
      "jourNaissance": 6,
      "rangNaissance": 5,
      "photo": "",
      "familleId": "famille-djongang",
      "grandeFamilleId": "djampou"
    },
    {
      "id": "joseph-emmanuel-tsafack-ngadji",
      "prenom": "Joseph Emmanuel",
      "nom": "Tsafack Ngadji",
      "sexe": "M",
      "moisNaissance": 1,
      "anneeNaissance": null,
      "jourNaissance": 9,
      "rangNaissance": 1,
      "photo": "photos/joseph-emmanuel-tsafack-ngadji.jpg",
      "familleId": "famille-bertin-bertin-epouse",
      "grandeFamilleId": "jouenang"
    },
    {
      "id": "charles-nguekam",
      "prenom": "Charles",
      "nom": "Nguekam",
      "sexe": "M",
      "moisNaissance": null,
      "anneeNaissance": null,
      "jourNaissance": null,
      "decede": true,
      "rangNaissance": null,
      "photo": "",
      "familleId": null,
      "grandeFamilleId": "tchoungang"
    },
    {
      "id": "moise-domkam",
      "prenom": "Moïse",
      "nom": "Domkam",
      "sexe": "M",
      "moisNaissance": null,
      "anneeNaissance": null,
      "jourNaissance": null,
      "decede": true,
      "rangNaissance": null,
      "photo": "",
      "familleId": null,
      "grandeFamilleId": "tchoungang"
    },
    {
      "id": "charles-nguekam-2",
      "prenom": "Charles",
      "nom": "Nguekam",
      "sexe": "",
      "moisNaissance": null,
      "anneeNaissance": null,
      "jourNaissance": null,
      "decede": true,
      "rangNaissance": null,
      "photo": "",
      "familleId": "tchoungang",
      "grandeFamilleId": "tchoungang"
    },
    {
      "id": "moise-domkam-2",
      "prenom": "Moïse",
      "nom": "Domkam",
      "sexe": "",
      "moisNaissance": null,
      "anneeNaissance": null,
      "jourNaissance": null,
      "decede": true,
      "rangNaissance": null,
      "photo": "",
      "familleId": "tchoungang",
      "grandeFamilleId": "tchoungang"
    },
    {
      "id": "francois-ngongang",
      "prenom": "François",
      "nom": "Gongang",
      "sexe": "M",
      "moisNaissance": null,
      "anneeNaissance": null,
      "jourNaissance": null,
      "rangNaissance": 1,
      "photo": "",
      "familleId": "famille-nguekam-2",
      "grandeFamilleId": "tchoungang"
    },
    {
      "id": "poupina-nguekam",
      "prenom": "Poupina",
      "nom": "Nguekam",
      "sexe": "F",
      "moisNaissance": null,
      "anneeNaissance": null,
      "jourNaissance": null,
      "rangNaissance": 3,
      "photo": "",
      "familleId": "famille-nguekam-2",
      "grandeFamilleId": "tchoungang"
    },
    {
      "id": "corine-nguekam",
      "prenom": "Corine",
      "nom": "Nguekam",
      "sexe": "F",
      "moisNaissance": null,
      "anneeNaissance": null,
      "jourNaissance": null,
      "rangNaissance": 4,
      "photo": "",
      "familleId": "famille-nguekam-2",
      "grandeFamilleId": "tchoungang"
    },
    {
      "id": "jean-tenkam",
      "prenom": "Jean",
      "nom": "Tenkam",
      "sexe": "M",
      "moisNaissance": null,
      "anneeNaissance": null,
      "jourNaissance": null,
      "decede": true,
      "rangNaissance": null,
      "photo": "photos/jean-tenkam.jpg",
      "familleId": null,
      "grandeFamilleId": "tchoungang"
    },
    {
      "id": "anne-ngoungue",
      "prenom": "Anne",
      "nom": "Ngoungue",
      "sexe": "F",
      "moisNaissance": null,
      "anneeNaissance": null,
      "jourNaissance": null,
      "decede": true,
      "rangNaissance": null,
      "photo": "photos/anne-ngoungue.jpg",
      "familleId": null,
      "grandeFamilleId": "tchoungang"
    },
    {
      "id": "irene-tiengoue",
      "prenom": "Irène",
      "nom": "Tiengoue",
      "sexe": "F",
      "moisNaissance": null,
      "anneeNaissance": null,
      "jourNaissance": null,
      "rangNaissance": null,
      "photo": "",
      "familleId": null,
      "grandeFamilleId": "tchoungang"
    },
    {
      "id": "nestor-momo",
      "prenom": "Nestor",
      "nom": "Toukuia",
      "sexe": "M",
      "moisNaissance": null,
      "anneeNaissance": null,
      "jourNaissance": null,
      "rangNaissance": null,
      "photo": "",
      "familleId": "famille-domkam",
      "grandeFamilleId": "tchoungang"
    },
    {
      "id": "joseph-momo",
      "prenom": "Joseph",
      "nom": "Momo",
      "sexe": "M",
      "moisNaissance": null,
      "anneeNaissance": null,
      "jourNaissance": null,
      "rangNaissance": null,
      "photo": "",
      "familleId": "famille-domkam",
      "grandeFamilleId": "tchoungang"
    },
    {
      "id": "emilienne-kouonang",
      "prenom": "Émilienne",
      "nom": "Kouonang",
      "sexe": "F",
      "moisNaissance": null,
      "anneeNaissance": null,
      "jourNaissance": null,
      "decede": true,
      "rangNaissance": 1,
      "photo": "",
      "familleId": "famille-koutchadjio",
      "grandeFamilleId": "jouenang"
    },
    {
      "id": "jeanette-guepnang",
      "prenom": "Jeanette",
      "nom": "Guepnang",
      "sexe": "F",
      "moisNaissance": null,
      "anneeNaissance": null,
      "jourNaissance": null,
      "decede": true,
      "rangNaissance": 2,
      "photo": "",
      "familleId": "famille-koutchadjio",
      "grandeFamilleId": "jouenang"
    },
    {
      "id": "tekam-samuel",
      "prenom": "Samuel",
      "nom": "Tekam",
      "sexe": "M",
      "moisNaissance": null,
      "anneeNaissance": null,
      "jourNaissance": null,
      "rangNaissance": 4,
      "photo": "",
      "familleId": "famille-koutchadjio",
      "grandeFamilleId": "jouenang"
    },
    {
      "id": "claudine-nono",
      "prenom": "Claudine",
      "nom": "Nono",
      "sexe": "F",
      "moisNaissance": null,
      "anneeNaissance": null,
      "jourNaissance": null,
      "decede": true,
      "rangNaissance": 5,
      "photo": "",
      "familleId": "famille-koutchadjio",
      "grandeFamilleId": "jouenang"
    },
    {
      "id": "gilbert-tchatchouang",
      "prenom": "Gilbert",
      "nom": "Tchatchouang",
      "sexe": "M",
      "moisNaissance": null,
      "anneeNaissance": null,
      "jourNaissance": null,
      "decede": true,
      "rangNaissance": null,
      "photo": "",
      "familleId": "famille-koutchadjio",
      "grandeFamilleId": "jouenang"
    },
    {
      "id": "meghane-djomo-jouenang",
      "prenom": "Meghane",
      "nom": "Djomo Jouenang",
      "sexe": "F",
      "moisNaissance": 3,
      "anneeNaissance": null,
      "jourNaissance": 19,
      "rangNaissance": null,
      "photo": "photos/meghane-djomo-jouenang.JPG",
      "familleId": "famille-jouenang",
      "grandeFamilleId": "jouenang"
    }
  ],
  "relations": [],
  "nouvelles": []
};
